// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rfzlluqlzjxortnptunh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmemxsdXFsemp4b3J0bnB0dW5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMDg2MjcsImV4cCI6MjA2ODU4NDYyN30.gdo02O3Su2OuvAUwUOR6ymjhDfIdNDfEKHPkGou7_fk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});